import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../component/Header/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <Header/>

        {/* Main Content */}
        <main className="bg-[#181818] text-white md:px-8 px-4 md:py-12 py-6 min-h-screen w-full md:mt-0 mt-12">
          {children}
        </main>
      </body>
    </html>
  );
}
